### ISSUE TITLE
Throws error when cancelled

### ISSUE THREAD

**Issue by green3g** [szchenghuang/debounce-async#1]
This lib is useful, but it throws a "cancelled" error when a debounced function is called multiple times. To work with node/browser promises, I would then need to "catch" this cancelled error..but in reality it should only throw if the promise returned by the debounced function throws. 

```javascript
debounce(() => {
    return new Promise((resolve, reject) => {
        // some logic here...
        resolve(); // should never throw an error

        // some more logic
        reject('Error message'); // this should throw
    });
});

**Comment by szchenghuang** [comment]
It rejects in order to tell which are ignored, and to notify the caller. If it resolves with nothing for the ignored, the caller needs to make a comparison between the resolved values in order to tell which is ignored and which is not. It becomes trickier.

**Comment by green3g** [comment]
Okay, I think that makes sense, maybe I'm just handling it incorrectly. Here's my situation:

```javascript
const debouncedAjax = debounce((params) => {
    return $.ajax('/api/items', params);
});

// else where in code
// function called whenever params change...this is debounced so if multiple params change quickly
// we don't call the ajax function each time
const result = debouncedAjax(params);

result.then(() => { alert('success!'); })
    .catch(e => { alert(e.message); }); // alerts "cancelled" every time....how do I prevent this?
```

**Comment by szchenghuang** [comment]
You are handling it fine. The caller is notified with the 'canceled' string. If it becomes a bit superfluous when it throws, you can make a string comparison in the `catch` clause and simply ignore the case with a noop.

**Comment by bradley-varol** [comment]
I have a use case where I don't want to handle errors with `catch()` so I'd love an argument to allow me to disable this feature. I'd like to be able to essentially force `shouldCancel` to always be false.
